const express=require("express");
const serverless=require("serverless-http");
const path=require("path");
const app=express();
app.use(express.json());
const notesRoutes=require("../server/routes/notes");
app.use("/notes",notesRoutes);
app.use("/",express.static(path.join(__dirname,"../public")));
module.exports=app;
module.exports.handler=serverless(app);